//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int id { get; set; }
        public Nullable<int> billId { get; set; }
        public Nullable<int> cakeId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Cake Cake { get; set; }
    }
}
