//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class Cake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cake()
        {
            this.BillDetails = new HashSet<BillDetail>();
        }
    
        public int id { get; set; }
        [Display(Name = "Type Cake")]
        public Nullable<int> typeId { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillDetail> BillDetails { get; set; }
        public virtual Type Type { get; set; }
    }

    public class CakeContext : DbContext
    {
        public virtual DbSet<Cake> Cakes { get; set; }

        public System.Data.Entity.DbSet<CakeStore.Models.Type> Types { get; set; }
    }
}
